volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    container_name: 'postgres'
    restart: always
    build:
      context: ./postgre
      dockerfile: Dockerfile
    volumes:
      - ./postgre/scripts/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: postgres -p ${POSTGRES_PORT}

  server:
    container_name: 'server'
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/server"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./server/:/server/
    environment:
      - ENV=local
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:${POSTGRES_PORT}", "--", "make", "run"]
