"""empty message

Revision ID: 34532ad5368d
Revises: 
Create Date: 2024-09-27 20:56:53.813010

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34532ad5368d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_item',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('link', sa.TEXT(), nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(516), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__video_item')),
        sa.UniqueConstraint('id', name=op.f('uq__video_item__id'))
    )
    op.create_index(
        "ix_video_item_embedding",
        "video_item",
        ["embedding"],
        postgresql_using='ivfflat',
        postgresql_ops={'embedding': 'vector_l2_ops'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_item')
    op.drop_index("ix_video_item_embedding")
    # ### end Alembic commands ###
