"""empty message

Revision ID: ad3bc9db1da0
Revises: 
Create Date: 2024-09-28 09:48:56.843370

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad3bc9db1da0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_item',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('link', sa.TEXT(), nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__video_item')),
        sa.UniqueConstraint('id', name=op.f('uq__video_item__id'))
    )
    op.create_table('video_frame',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('video_item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.ForeignKeyConstraint(['video_item_id'], ['video_item.id'], name=op.f('fk__video_frame__video_item_id__video_item')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__video_frame')),
        sa.UniqueConstraint('id', name=op.f('uq__video_frame__id'))
    )
    op.create_index('ix_video_item_embedding', 'video_frame', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_item_embedding', table_name='video_frame', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('video_frame')
    op.drop_table('video_item')
    # ### end Alembic commands ###
